typography_spectrum: 0.4213951120618731
content_rating:
  adult: false
color:
  lightness: 0.9252282555680722
  brandColors:
    - '#6C6E58'
    - '#3E423A'
    - '#417378'
    - '#A4CFBE'
    - '#F4F7D9'
  saturation: 0.87869508494623
  brandStrength: 0.8071518233045936
  rhythmicContrast: 0.08260581619106233
github: true
opengraph: {}
layout_spectrum: 0.7437183200381696
analytics: {}
author: {}
name: communicating.space
url: 'https://communicating.space/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: About
    id: 9de519c3-aac1-43f6-ae29-343e7839a17f
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Communicating Space
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/a1117ce1-6fbd-49f9-872e-8ec409145c65.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/a1117ce1-6fbd-49f9-872e-8ec409145c65.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/8b7fe009-aaae-4555-a823-8ab83c19a6b6.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/8b7fe009-aaae-4555-a823-8ab83c19a6b6.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  We collect, publish, and promote space related activities. Earth Observation,
  Telecommunications, Space Flight, are just some of the topics!
