name: spacefolder
analytics: {}
github: true
description: sdwsedsawfb ffd fdgds fgds
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
author: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/06f447f1-9404-45c7-9ade-6c9153d7f400.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/06f447f1-9404-45c7-9ade-6c9153d7f400.png
    metadata:
      author: []
      '@context': 'http://schema.org'
      keywords: []
      '@type': MediaObject
      publisher:
        favicon: null
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      app_links: []
      related: []
      description: ''
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
navigation:
  - id: da8c25d5-5e7c-4002-885e-e99ad131e454
    name: BusinessCollection
    type: content
  - id: 8fc93172-5fd4-4630-8744-59154dea6cdf
    name: About
    type: content
layout_spectrum: 0.7437183200381696
color:
  lightness: 0.9252282555680722
  brandColors:
    - '#6C6E58'
    - '#3E423A'
    - '#417378'
    - '#A4CFBE'
    - '#F4F7D9'
  saturation: 0.87869508494623
  brandStrength: 0.8071518233045936
  rhythmicContrast: 0.08260581619106233
content_rating:
  adult: false
typography_spectrum: 0.4213951120618731
opengraph: {}
title: A collection of space
